apiVersion: apps/v1
kind: Deployment
metadata:
  name: reddytalk-voice-gateway
  labels:
    app: reddytalk
    component: voice-gateway
spec:
  replicas: 3
  selector:
    matchLabels:
      app: reddytalk
      component: voice-gateway
  template:
    metadata:
      labels:
        app: reddytalk
        component: voice-gateway
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9090"
        prometheus.io/path: "/metrics"
    spec:
      serviceAccountName: reddytalk-sa
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        fsGroup: 2000
      containers:
      - name: voice-gateway
        image: reddytalk.azurecr.io/voice-gateway:latest
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 8081
          name: websocket
          protocol: TCP
        - containerPort: 9090
          name: metrics
          protocol: TCP
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "8080"
        - name: WEBSOCKET_PORT
          value: "8081"
        - name: METRICS_PORT
          value: "9090"
        envFrom:
        - secretRef:
            name: reddytalk-secrets
        - configMapRef:
            name: reddytalk-config
        resources:
          requests:
            memory: "4Gi"
            cpu: "2"
            ephemeral-storage: "1Gi"
          limits:
            memory: "8Gi"
            cpu: "4"
            ephemeral-storage: "2Gi"
        livenessProbe:
          httpGet:
            path: /health/live
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 2
        volumeMounts:
        - name: cache-volume
          mountPath: /app/cache
        - name: secrets-store
          mountPath: /mnt/secrets
          readOnly: true
      volumes:
      - name: cache-volume
        emptyDir:
          sizeLimit: 10Gi
      - name: secrets-store
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: "reddytalk-kv"
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - reddytalk
            topologyKey: kubernetes.io/hostname
      tolerations:
      - key: "kubernetes.azure.com/scalesetpriority"
        operator: "Equal"
        value: "spot"
        effect: "NoSchedule"