version: '3.8'

services:
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n-local
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - NODE_ENV=production
      - N8N_BASIC_AUTH_ACTIVE=false
      - N8N_ENCRYPTION_KEY=your-encryption-key-here
      - DB_TYPE=sqlite
      - DB_SQLITE_DATABASE_FILE=/home/node/.n8n/database.sqlite
      - N8N_USER_MANAGEMENT_DISABLED=false
      - N8N_SMTP_HOST=
      - N8N_SMTP_PORT=
      - N8N_SMTP_USER=
      - N8N_SMTP_PASS=
      - N8N_SMTP_SENDER=
    volumes:
      - ./n8n_data:/home/node/.n8n
      - ./local_files:/files
    restart: unless-stopped