apiVersion: v1
kind: Service
metadata:
  name: reddytalk-voice-gateway
  labels:
    app: reddytalk
    component: voice-gateway
spec:
  type: ClusterIP
  selector:
    app: reddytalk
    component: voice-gateway
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  - name: websocket
    port: 8081
    targetPort: 8081
    protocol: TCP
  - name: metrics
    port: 9090
    targetPort: 9090
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: reddytalk-loadbalancer
  labels:
    app: reddytalk
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "false"
spec:
  type: LoadBalancer
  selector:
    app: reddytalk
    component: voice-gateway
  ports:
  - name: http
    port: 80
    targetPort: 8080
  - name: websocket
    port: 8081
    targetPort: 8081